In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("Student_Performance.csv")

In [9]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [8]:
df.tail()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [9]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [11]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [14]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [ ]:
! pip install sklearn

In [2]:
# from scikit-learn.preprocessing import LabelEncoder, standardScaler
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [6]:
le = LabelEncoder()
df["Extracurricular Activities"] = le.fit_transform(df["Extracurricular Activities"])

NameError: name 'df' is not defined

In [4]:
df

NameError: name 'df' is not defined

In [29]:
x = df[["Hours Studied","Previous Scores",	"Extracurricular Activities",	"Sleep Hours",	"Sample Question Papers Practiced"]]

In [ ]:
y= df["Performance Index"]
y

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

In [51]:
scaler = StandardScaler()
x_train_scaled =  scaler.fit_transform(x_train)

In [52]:
x_test_scaled = scaler.fit_transform(x_test)

In [53]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_error

In [54]:
model = LinearRegression()
model.fit(x_train_scaled, y_train)

LinearRegression()

In [58]:
y_pred = model.predict(x_test_scaled)

In [55]:
model.predict(x_test_scaled)

array([59.50398209, 44.87258006, 32.05267398, ..., 37.33314748,
       41.04075574, 40.81120407], shape=(2000,))

In [56]:
mean_squared_error(y_test, model.predict(x_test_scaled))

4.270225941089683

In [59]:
r2_score(y_test , y_pred)

0.988354612764344

In [67]:
import pickle
with open("student_lr_model.pkl", "wb") as f:
    pickle.dump((model,scaler,le),f)

In [5]:
df.head()

NameError: name 'df' is not defined

In [6]:
df.tail()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [6]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [8]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [9]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [17]:
le = LabelEncoder()
df["Extracurricular Activities"] = le.fit_transform(df["Extracurricular Activities"])

In [18]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [19]:
x = df[["Hours Studied","Previous Scores",	"Extracurricular Activities",	"Sleep Hours",	"Sample Question Papers Practiced"]]

In [20]:
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [22]:
y = df["Performance Index"]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=.2)

In [ ]:
x_train

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6513,2,49,0,9,9
555,5,82,1,4,1
9806,4,65,1,8,6
9382,3,73,0,8,0
2565,9,44,1,4,0
...,...,...,...,...,...
8836,7,60,1,5,5
1136,2,74,0,5,2
9305,9,99,1,7,5
4239,3,81,0,8,3
4921,7,75,1,8,4

In [26]:
x_test

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
3957,2,92,0,4,3
9252,9,62,0,7,3
7874,4,81,0,7,6
339,4,89,1,7,1
9269,5,82,0,9,4
...,...,...,...,...,...
5060,6,74,1,8,6
4233,8,94,0,9,1
6535,6,58,1,9,8
6141,8,45,1,4,6
7850,8,84,0,9,5

In [28]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error , r2_score , mean_absolute_error

In [30]:
model = LinearRegression()
model.fit(x_train_scaled , y_train)

LinearRegression()

In [35]:
y_pred = model.predict(x_test_scaled)

In [32]:
x_test_scaled

array([[-1.13011951,  1.33410897, -1.0010005 , -1.50001443, -0.54483162],
       [ 1.56522515, -0.40644939, -1.0010005 ,  0.27795605, -0.54483162],
       [-0.36002104,  0.69590424, -1.0010005 ,  0.27795605,  0.5073054 ],
       ...,
       [ 0.41007744, -0.63852383,  0.9990005 ,  1.46326971,  1.20873008],
       [ 1.18017591, -1.39276579,  0.9990005 , -1.50001443,  0.5073054 ],
       [ 1.18017591,  0.86996008, -1.0010005 ,  1.46326971,  0.15659306]])

In [34]:
model.predict([[-1.13011951,  1.33410897, -1.0010005 , -1.50001443, -0.54483162]])

array([68.80193901])

In [36]:
mean_squared_error(y_test , y_pred)

4.778170366609223

In [37]:
r2_score(y_test , y_pred)

0.9871399765369615

In [38]:
import pickle
with open("student_lr_final_model.pkl" , 'wb') as file :
    pickle.dump((model,scaler,le),file)